### ISSUE TITLE
Initial provisioning of elasticsearch doesn't work

### ISSUE THREAD

**Issue by RobQuistNL** [Enrise/elasticsearch-formula#25]
On the first provision of a machine that has elasticsearch enabled, the service won't start. After a second run it works just fine.

```
----------
          ID: elasticsearch
    Function: service.running
      Result: False
     Comment: Service elasticsearch has been enabled, and is dead
     Started: 16:27:08.634264
    Duration: 144.244 ms
     Changes:   
              ----------
              elasticsearch:
                  True
```

Pillar:
```
elasticsearch:
  version: 1.4.5
  repo_version: 1.4
```
